service: faaskeeper-microbenchmark-queue

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  environment:
    DYNAMODB_TABLE: BENCHMARK_QUEUE

functions:
  benchmarker:
    handler: function/benchmark.benchmarker
    reservedConcurrency: 1
    timeout: 30
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          startingPosition: LATEST
          maximumRetryAttempts: 3
          arn:
            Fn::GetAtt:
              - dynamoQueue
              - StreamArn
      - sqs:
          arn:
            Fn::GetAtt:
              - sqsQueueLatency
              - Arn
      - sqs:
          arn:
            Fn::GetAtt:
              - sqsQueueLatencyFIFO
              - Arn
      - http:
          method: POST
          path: latency

  benchmarker_multiple:
    handler: function/benchmark_multiple.benchmarker
    reservedConcurrency: 1
    timeout: 30
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - sqsQueueThroughputFIFO
              - Arn
          batchSize: 10
          maximumBatchingWindow: 0

      - sqs:
          arn:
            Fn::GetAtt:
              - sqsQueueThroughput
              - Arn
          batchSize: 10
          maximumBatchingWindow: 0
 
      - http:
          method: POST
          path: throughput

resources:
  Resources:
    dynamoQueue:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: BENCHMARK_DYNAMO_QUEUE
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        StreamSpecification:
          StreamViewType: NEW_IMAGE
    dynamoQueueThroughput:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: BENCHMARK_DYNAMO_QUEUE_THROUGHPUT
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        StreamSpecification:
          StreamViewType: NEW_IMAGE
    sqsQueueThroughputFIFO:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: BENCHMARK_SQS_QUEUE.fifo
        FifoQueue: True
        DelaySeconds: 0
    sqsQueueThroughput:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: BENCHMARK_SQS_QUEUE
        DelaySeconds: 0
    sqsQueueLatencyFIFO:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: BENCHMARK_SQS_QUEUE_LATENCY.fifo
        FifoQueue: True
        DelaySeconds: 0
    sqsQueueLatency:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: BENCHMARK_SQS_QUEUE_LATENCY
        DelaySeconds: 0

plugins:
  - serverless-iam-roles-per-function

